name: BeaconPlugin
version: 1.0.0
main: com.noxar3s.BeaconPlugin
description: Beacon in pairs plugin
author: NoXAr3s
website: https://papermc.io
api-version: '1.21.4'
commands:
  startgame:
    description: Starts the beacon game.
    usage: /startgame
    permission: beaconplugin.startgame
  giveweapons:
    description: Gives random weapons to all players
    usage: /giveweapons
    permission: beaconplugin.giveweapons
permissions:
  beaconplugin.startgame:
    description: Allows starting the game
    default: op
  beaconplugin.giveweapons:
    description: Allows giving weapons to all players
    default: op